//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vmail
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int id { get; set; }
        public string messageID { get; set; }
        public string sender { get; set; }
        public string subject { get; set; }
        public string content_view { get; set; }
        public string date { get; set; }
        public Nullable<bool> read { get; set; }
        public Nullable<bool> attachment { get; set; }
    }
}
